# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (20)
# #########################################################################

class AdaptedEmployer(BaseModel):
    employer: typing.Optional[str] = None
    description: typing.Optional[str] = None
    positions: typing.Optional["AdaptedPosition"] = None
    matching_score: typing.Optional[str] = None
    matching_reasons: typing.Optional[str] = None

class AdaptedPosition(BaseModel):
    title: typing.Optional[str] = None
    description: typing.Optional[str] = None
    responsibilities: typing.List[str]
    competencies: typing.List[str]
    technical_proficiencies: typing.List[str]

class CompanyBrand(BaseModel):
    golden_circle: typing.Optional["GoldenCircle"] = None
    customer_segments: typing.List[str]
    writing_examples: typing.List["WritingExample"]

class CompanyService(BaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None

class CompetenciesAndSkills(BaseModel):
    competency: typing.Optional[str] = None
    soft_skills: typing.List[str]
    hard_skills: typing.List[str]

class Competency(BaseModel):
    competency: typing.Optional[str] = None
    soft_skills: typing.List[str]
    hard_skills: typing.List[str]

class CompetencyAndSkills(BaseModel):
    competency: typing.Optional[str] = None
    skills: typing.List[str]

class ContractDetails(BaseModel):
    type: typing.Optional[str] = None
    duration: typing.Optional[str] = None
    time_commitment: typing.Optional[str] = None
    work_mode: typing.Optional[str] = None

class CoverLetter(BaseModel):
    subject_line: typing.Optional[str] = None
    salutation: typing.Optional[str] = None
    introduction_paragraph: typing.Optional[str] = None
    teaser_paragraph: typing.Optional[str] = None
    contribution_paragraph: typing.Optional[str] = None
    closure_paragraph: typing.Optional[str] = None

class EmploymentRecord(BaseModel):
    employer: typing.Optional[str] = None
    description: typing.Optional[str] = None
    position: typing.Optional["JobPosition"] = None
    match_explanation: typing.Optional[str] = None
    match_index: typing.Optional[int] = None

class EmploymentRecordInput(BaseModel):
    employer: typing.Optional[str] = None
    description: typing.Optional[str] = None
    property_job_titles: typing.List[str]
    positions: typing.List["JobPosition"]

class Formation(BaseModel):
    degree: typing.Optional[str] = None
    institution: typing.Optional[str] = None
    location: typing.Optional[str] = None
    specializations: typing.List["Specialization"]

class GoldenCircle(BaseModel):
    why: typing.Optional[str] = None
    how: typing.Optional[str] = None
    what: typing.List["CompanyService"]

class JobPosition(BaseModel):
    title: typing.Optional[str] = None
    description: typing.Optional[str] = None
    responsibilities: typing.List[str]
    competencies: typing.List[str]
    technical_proficiencies: typing.List[str]

class JobPosting(BaseModel):
    title: typing.Optional[str] = None
    company: typing.Optional[str] = None
    location: typing.Optional[str] = None
    contract_details: typing.Optional["ContractDetails"] = None
    language_skills: typing.List["LanguageSkills"]
    description: typing.Optional[str] = None
    competencies_and_skills: typing.List["CompetenciesAndSkills"]
    roles: typing.List[str]
    requirements: typing.List[str]
    recruiter_details: typing.Optional["RecruiterDetails"] = None
    posting_date: typing.Optional[str] = None
    application_deadline: typing.Optional[str] = None
    salary_range: typing.Optional[str] = None
    benefits: typing.List[str]

class LanguageSkills(BaseModel):
    english_level: typing.Optional[str] = None
    german_level: typing.Optional[str] = None
    language_of_posting: typing.Optional[str] = None
    languages: typing.Optional[str] = None

class ProfileCoverLetterAndEmail(BaseModel):
    professional_profile: typing.Optional[str] = None
    email_body: typing.Optional[str] = None
    competencies_and_skills: typing.List["CompetencyAndSkills"]
    cover_letter: typing.Optional["CoverLetter"] = None

class RecruiterDetails(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    phone: typing.Optional[str] = None

class Specialization(BaseModel):
    focus: typing.Optional[str] = None
    description: typing.Optional[str] = None

class WritingExample(BaseModel):
    style: typing.Optional[str] = None
    tone: typing.Optional[str] = None
    example: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
