# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CompetenciesAndSkills": types.CompetenciesAndSkills,
    "stream_types.CompetenciesAndSkills": stream_types.CompetenciesAndSkills,

    "types.Competency": types.Competency,
    "stream_types.Competency": stream_types.Competency,

    "types.ContractDetails": types.ContractDetails,
    "stream_types.ContractDetails": stream_types.ContractDetails,

    "types.EmploymentRecord": types.EmploymentRecord,
    "stream_types.EmploymentRecord": stream_types.EmploymentRecord,

    "types.JobPosition": types.JobPosition,
    "stream_types.JobPosition": stream_types.JobPosition,

    "types.JobPosting": types.JobPosting,
    "stream_types.JobPosting": stream_types.JobPosting,

    "types.LanguageSkills": types.LanguageSkills,
    "stream_types.LanguageSkills": stream_types.LanguageSkills,

    "types.RecruiterDetails": types.RecruiterDetails,
    "stream_types.RecruiterDetails": stream_types.RecruiterDetails,


}