# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CompetenciesAndSkills": types.CompetenciesAndSkills,
    "stream_types.CompetenciesAndSkills": stream_types.CompetenciesAndSkills,

    "types.ContractDetails": types.ContractDetails,
    "stream_types.ContractDetails": stream_types.ContractDetails,

    "types.JobPosting": types.JobPosting,
    "stream_types.JobPosting": stream_types.JobPosting,

    "types.LanguageSkills": types.LanguageSkills,
    "stream_types.LanguageSkills": stream_types.LanguageSkills,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,


}